server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: master
