server:
  port: 1000
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: gateway1000
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
#        - id: mall-auth
#          uri: lb://mall-auth
#          predicates:
#            - Path=/mall-auth/**
#          filters:
#            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
#        - id: mall-portal
#          uri: lb://mall-portal
#          predicates:
#            - Path=/mall-portal/**
#          filters:
#            - StripPrefix=1
#        - id: mall-search
#          uri: lb://mall-search
#          predicates:
#            - Path=/mall-search/**
#          filters:
#            - StripPrefix=1
#        - id: mall-demo
#          uri: lb://mall-demo
#          predicates:
#            - Path=/mall-demo/**
#          filters:
#            - StripPrefix=1