server:
  port: 8085
spring:
  datasource:
    username: zhengshukai
    password: ZHENGshukai
    url: jdbc:mysql://rm-wz9qo2um0eygb0a6qso.mysql.rds.aliyuncs.com:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  profiles:
    active: dev
  #    redis配置(这是豪的服务器地址，注意更换）
  redis:
    host: 47.106.183.207
    port: 6379
    database: 0

#\u65E5\u5FD7\u914D\u7F6E
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/images/mapper/xml/*Mapper.xml
  type-aliases-package: images.entity
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
    #      使用eureka记得下面俩改为true
    fetch-registry: false
    register-with-eureka: false
  instance:
    instance-id: usr8081
    prefer-ip-address: true

##    120.25.217.98